# **Worksheet 0**

# 4.1 Exercise on Functions:

**Task 1**

In [ ]:
def length_conversion(value, conversion_type):
  """
  convert length between meter and feet

  Parameters:
  value (float): The value to be converted.
  conversion_type (str): The type of conversion ('m_to_ft' or 'ft_to_m').

  """
  if conversion_type == 'm_to_ft':
    return value * 3.28084 #1 meter = 3.28084 feet
  elif conversion_type == 'ft_to_m':
    return value / 3.28084 #1 foot = 0.3048 meter
  else:
    return None

def weigth_conversion(value, conversion_type):
  """
  convert length between kilogram and pounds

  Parameters:
  value (float): The value to be converted.
  conversion_type (str): The type of conversion ('kg_to_lbs' or 'lbs_to_kg').

  """
  if conversion_type == 'kg_to_lbs':
    return value * 2.20462 #1 kg = 2.20462 lbs
  elif conversion_type == 'lbs_to_kg':
      return value / 2.20462 #1 lbs = 0.453592 kg
  else:
    return None

def volume_conversion(value, conversion_type):
  """
  convert length between liter and gallon

  Parameters:
  value (float): The value to be converted.
  conversion_type (str): The type of conversion ('L_to_gal' or 'gal_to_L').

  """
  if conversion_type == 'L_to_gal':
    return value * 0.264172  # 1 liter = 0.264172 gallons
  elif conversion_type == 'gal_to_L':
      return value / 0.264172  # 1 gallon = 3.78541 liters
  else:
    return None


def main():
  """
  main function to run the program
  """
  print("Welcome to the length conversion program! \n")
  print("Please select an option:")
  print("1. Convert Length")
  print("2. Convert Weight")
  print("3. Convert Volume \n")

  try:
    choice = int(input("Enter your Choice 1, 2 and 3: "))
    if choice not in [1,2,3]:
      print("Please enter number between 1, 2 and 3")
      return

    value = float(input("Enter value to convert: "))

    if choice == 1:
      print("1: Convert meter to feet")
      print("2. Convert feet to meter")
      length_choice = int(input("Enter Your choice (1/2): "))
      conversion_type = 'm_to_ft' if length_choice == 1 else 'ft_to_m'
      result = length_conversion(value, conversion_type)

    elif choice == 2:
      print("1: Convert meter to feet")
      print("2. Convert feet to meter")
      weight_choice = int(input("Enter Your choice (1/2): "))
      conversion_type = 'kg_to_lbs' if weight_choice == 1 else 'lbs_to_kg'
      result = weigth_conversion(value, conversion_type)

    elif choice == 3:
      print("1: Convert meter to feet")
      print("2. Convert feet to meter")
      volume_choice = int(input("Enter Your choice (1/2): "))
      conversion_type = 'L_to_gal' if volume_choice == 1 else 'gal_to_L'
      result = volume_conversion(value, conversion_type)

    print(f"converted value : {result:4f}")

  except ValueError:
    print("Invalid Input! please enter a numeric value")

if __name__ == '__main__':
  main()

Welcome to the length conversion program! 

Please select an option:
1. Convert Length
2. Convert Weight
3. Convert Volume 

Enter your Choice 1, 2 and 3: 1
Enter value to convert: 20
1: Convert meter to feet
2. Convert feet to meter
Enter Your choice (1/2): 1
converted value : 65.616800


**Task 2**

In [ ]:
# Python program that performs various mathematical operations on a list of numbers.

def calculate_sum(numbers):
  """
    Calculate the sum of a list of numbers using a for loop.

    Parameters:
    numbers (list): A list of numeric values.

    Returns:
    float: Sum of numbers.
  """
  total = 0
  for num in numbers:
    total += num
  return total

def calculate_average(numbers):
  """
   Calculate the average of a list of numbers using a for loop.

   Parameters:
   numbers (list): A list of numeric values.

   Returns:
   float: Average value.
  """
  totaL= 0
  count = 0
  for num in numbers:
    total += num
    count += 1
  return total / count if count > 0 else 0

def calculate_maximun(numbers):
  """
   Find the maximum value in a list of numbers using a for loop.

   Parameters:
   numbers (list): A list of numeric values.

   Returns:
   float: Maximum value.
  """
  max_value = numbers[0]
  for num in numbers:
    if num>max_value:
      max_value = num
  return max_value

def calculate_minimum(numbers):
  """
   Find the minimum value in a list of numbers using a for loop.

   Parameters:
   numbers (list): A list of numeric values.

   Returns:
   float: Minimum value.
  """
  min_value = numbers[0]
  for num in numbers:
    if num<min_value:
      min_value = num
  return min_value


def main():
  """
  main function to run the program
  """
  print("Math operation on a list of Numbers")
  print("Choose an operation")
  print("1. Sum")
  print("2. Average")
  print("3. Maximum")
  print("4. Minimum")

  try:
    choice = int(input("Enter your choice (1/2/3/4): "))
    if choice not in [1,2,3,4]:
      print("Invalid choice! please select between 1, 2, 3 and 4")
      return

    numbers = input("Enter number separated by spaces: ").split()
    numbers = [float(num) for num in numbers]

    if not numbers:
      print("Error: No number provided")

    if choice == 1:
      result = calculate_sum(numbers)
      operation = "Sum"

    elif choice == 2:
      result = calculate_average(numbers)
      operation = "Average"

    elif choice == 3:
      result = calculate_maximun(numbers)
      operation = "Maximum"

    elif choice == 4:
      result = calculate_minimum(numbers)
      operation = "Minimum"

    print(f"{operation} of {numbers} is {result}")

  except ValueError:
    print("Invalid input please enter a numeric value only")

if __name__ == '__main__':
  main()

Math operation on a list of Numbers
Choose an operation
1. Sum
2. Average
3. Maximum
4. Minimum
Enter your choice (1/2/3/4): 1
Enter number separated by spaces: 20 20
Sum of [20.0, 20.0] is 40.0


# 4.2 Exercise on List Manipulation:

In [ ]:
#1 Extract Every other element

def extract_every_other(lst):
  """
  Extracts every other element from a list, starting from the first element.

  Parameters:
  lst (list): The input list.

  Returns:
  list: A new list containing every other element from the input list.
  """
  return lst[::2]

#2 Slice a sublist

def get_sublist(lst, start, end):
  """
  Extracts a sublist from a given list based on specified start and end indices.

  Parameters:
  lst (list): The input list.
  start (int): The starting index for the sublist.
  end (int): The ending index for the sublist.

  Returns:
  list: A new list containing the elements from the input list within the specified
  """
  return lst[start:end+1]

#3 Reverse a List using slicing

def reverse_list(lst):
  """
  Reverses a list using slicing.

  Parameters:
  lst (list): The input list.

  Return:
  List: a reversed List
  """
  return lst[::-1]

#4 Remove the first and last element

def remove_first_last(lst):
  """
  Removes the first and last elements of a list and returns the resulting sublist.

  Parameters:
  lst(list): The input list.

  Returns:
  list: A new list containing all elements except the first and last elements of the input list.
  """
  return lst[1:-1]

#5. Get the first n element

def get_first_n(lst, n):
  """
  Extracts the first n elements from a list.

  Parameters:
  lst (list): The input list.
  n (int): Number of elements to extract.

  Returns:
  list: A new list containing the first n elements from the input list.
  """
  return lst[:n]

#6. Extract Element from the end

def get_last_n(lst, n):
  """
  Extracts the last n elements from a list using slicing.

  Parameters:
  lst (list): The input list.
  n (int): Number of elements to extract from the end.

  Returns:
  list: A new list containing the last n elements.
  """
  return lst[-n:]

#7. Extract Element in reverse order

def reverse_skip(lst):
  """
  Extracts elements in reverse order, skipping one in between, starting from the second-to-last element.

  Parameters:
  lst (list): The input list.

  Returns:
  list: A new list containing elements in reverse order, skipping one in between, starting from the second-to-last element.
  """
  return lst[-2::-2]

#Example list
sample_list =  [1,2,3,4,5,6]

print("1. Extract every other element:", extract_every_other(sample_list))
print("2. Sublist (2 to 4):", get_sublist(sample_list, 2, 4))
print("3. Reversed list:", reverse_list(sample_list))
print("4. Without first & last:", remove_first_last(sample_list))
print("5. First 3 elements:", get_first_n(sample_list, 3))
print("6. Last 2 elements:", get_last_n(sample_list, 2))
print("7. Reverse skip:", reverse_skip(sample_list))

1. Extract every other element: [1, 3, 5]
2. Sublist (2 to 4): [3, 4, 5]
3. Reversed list: [6, 5, 4, 3, 2, 1]
4. Without first & last: [2, 3, 4, 5]
5. First 3 elements: [1, 2, 3]
6. Last 2 elements: [5, 6]
7. Reverse skip: [5, 3, 1]


# 4.3 Exercise on Nested List:

In [ ]:
#1. flatten a Nested List

def flatten(lst):
  """
  Flattens a nested list into a single list.

  Parameters:
  lst (list): The input nested list.

  Returns:
  list: A new list containing all the elements from the nested list.
  """
  result = []
  for sublist in lst:
    if isinstance(sublist, list):
      result.extend(flatten(sublist))
    else:
      result.append(sublist)
  return result

#2. Accessing Nested List Elements
def access_nested_element(lst, indices):
  """
  Extracts a specific element from a nested list given its indices.

  Parameters:
  lst (list): The input nested list.
  indices (list): The indices specifying the path to the element.

  Return:
  The extracted element.
  """
  element = lst
  for index in indices:
    element = element[index]
  return element

#3. Sum of All Elements in a Nested List

def sum_nested(lst):
  """
  Calculates the sum of all numbers in a nested list, regardless of depth.

  Parameters:
  lst (list): The input nested list.

  Returns:
  int/float: The sum of all elements.
  """
  total = 0
  for item in lst:
    if isinstance(item, list):
      total += sum_nested(item)
    else:
      total +=item
  return total

# 4. Remove Specific Element from a Nested List

def remove_element(lst, elem):
  """
  Removes all occurrences of a specific element from a nested list.

  Parameters:
  lst (list): The input nested list.
  elem: The element to remove.

  Returns:
  list: A new list with all occurrences of the specified element removed.
  """
  result = []
  for item in lst:
    if isinstance(item, list):
      filtered_list = remove_element(item, elem)
      if filtered_list:
        result.append(filtered_list)
    elif item != elem:
      result.append(item)
  return result

# 5. Find the Maximum Element in a Nested List

def find_max(lst):
  """
  Finds the maximum element in a nested list.

  Parameters:
  lst (list): The input nested list.

  Returns:
  The maximum element.
  """
  max_value = float('-inf')
  for item in lst:
    if isinstance(item, list):
      max_value = max(max_value, find_max(item))
    else:
      max_value = max(max_value, item)
  return max_value

#6. Count Occurrences of an Element in a Nested List

def count_occurrences(lst, elem):
  """
  Counts the occurrences of a specific element in a nested list.

  Parameters:
  lst (list): The input nested list.
  elem: The element to count.

  Returns:
  int: The number of occurrences of elem.
  """
  count = 0
  for item in lst:
    if isinstance(item, list):
      count += count_occurrences(item, elem)
    elif item == elem:
      count +=1
  return count

#7. Flatten a List of Lists of Lists

def deep_flatten(lst):
  """
  Flattens a deeply nested list into a single list.

  Parameters:
  lst (list): The input deeply nested list.
  Returns:
  list: A new list containing all the elements from the deeply nested list.
  """
  result = []
  for item in lst:
    if isinstance(item, list):
      result.extend(deep_flatten(item))
    else:
      result.append(item)
  return result

# 8. Nested List Average

def average_nested(lst):
  """
   Calculates the average of all elements in a nested list.

   Parameters:
   lst (list): The input nested list.

   Returns:
   float: The average of all elements.
  """
  flat_list = deep_flatten(lst)
  return sum(flat_list) / len(flat_list) if flat_list else 0


#Example Input list
nested_list_1 = [[1,2],[3,4],[5]]
nested_list_2 = [[1,2,3],[4,5,6],[7,8,9]]
nested_list_3 = [[1,2],[3,[4,5]],6]
nested_list_4 = [[1,2],[3,2],[4,5]]
nested_list_5 = [[[1,2],[3,4]],[[5,6],[7,8]]]


print("1. Flatten a Nested List: ", flatten(nested_list_1))
print("2. Access Nested Element (index [1,2]): ", access_nested_element(nested_list_2, [1,2]))
print("3. Sum of All Elements:", sum_nested(nested_list_3))
print("4. Remove Element (elem=2):", remove_element(nested_list_4, 2))
print("5. Max Element in Nested List:", find_max(nested_list_3))
print("6. Count Occurrences (elem=2):", count_occurrences(nested_list_4, 2))
print("7. Deep Flatten:", deep_flatten(nested_list_5))
print("8. Average of Nested List:", average_nested([[1, 2], [3, 4], [5, 6]]))

1. Flatten a Nested List:  [1, 2, 3, 4, 5]
2. Access Nested Element (index [1,2]):  6
3. Sum of All Elements: 21
4. Remove Element (elem=2): [[1], [3], [4, 5]]
5. Max Element in Nested List: 6
6. Count Occurrences (elem=2): 2
7. Deep Flatten: [1, 2, 3, 4, 5, 6, 7, 8]
8. Average of Nested List: 3.5


# NumPy

**Problem - 1: Array Creation:**


In [ ]:
import numpy as np

empty_array = np.empty((2, 2))
print("Empty Array (2x2):\n", empty_array, "\n")

ones_array = np.ones((4,2))
print("Ones Array (4x2): \n", ones_array,"\n")

fill_array = np.full((3,3),5)
print("Array filled with 5: \n", fill_array,"\n")

sample_array = np.array([[1,2,3], [4,5,6]])
zero_like_array = np.zeros_like(sample_array)
print("Zeros Like Array: \n", zero_like_array,"\n")

ones_like_array = np.ones_like(sample_array)
print("Ones Like Array: \n", ones_like_array,"\n")

new_list = [1,2,3,4]
numpy_array = np.array(new_list)
print("Numpy Array from List: \n", numpy_array,"\n")

Empty Array (2x2):
 [[4.9e-324 9.9e-324]
 [1.5e-323 2.0e-323]] 

Ones Array (4x2): 
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]] 

Array filled with 5: 
 [[5 5 5]
 [5 5 5]
 [5 5 5]] 

Zeros Like Array: 
 [[0 0 0]
 [0 0 0]] 

Ones Like Array: 
 [[1 1 1]
 [1 1 1]] 

Numpy Array from List: 
 [1 2 3 4] 



**Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:**

In [32]:
arr_10_to_49 = np.arange(10,50)
print("Array of Integers from 10 to 49: \n", arr_10_to_49,"\n")

matrix_0_to_8 = np.arange(0,9).reshape(3,3)
print("3x3 Matrix with values ranging from 0 to 8: \n", matrix_0_to_8,"\n")

identity_matrix = np.eye(3)
print("3x3 Identity Matrix: \n", identity_matrix,"\n")

random_matrix = np.random.random(30)
mean_value = np.mean(random_matrix)
print("Mean Value of Random Matrix: \n", mean_value,"\n")

random_matrix = np.random.random((10,10))
min_value = np.min(random_matrix)
max_value = np.max(random_matrix)
print("Min Value of Random Matrix: \n", min_value,"\n")
print("Max Value of Random Matrix: \n", max_value,"\n")

zero_array = np.zeros(10)
zero_array[4] = 1
print("Array with Value 1 at Index 4: \n", zero_array,"\n")

arr = np.array([1,2,0,0,5,6,0,8])
reversed_array = arr[::-1]
print("Reversed Array: \n", reversed_array,"\n")

border_array = np.ones((5,5))
border_array[1:-1, 1:-1] = 0
print("Array with Border Ones: \n", border_array,"\n")

checkboard = np.zeros((8,8), dtype=int)
checkboard[1::2, ::2] = 1
checkboard[::2, 1::2] = 1
print("Checkboard Pattern: \n", checkboard,"\n")

Array of Integers from 10 to 49: 
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49] 

3x3 Matrix with values ranging from 0 to 8: 
 [[0 1 2]
 [3 4 5]
 [6 7 8]] 

3x3 Identity Matrix: 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 

Mean Value of Random Matrix: 
 0.5196135357311756 

Min Value of Random Matrix: 
 0.0007800247921305736 

Max Value of Random Matrix: 
 0.9986763128393974 

Array with Value 1 at Index 4: 
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.] 

Reversed Array: 
 [8 0 6 5 0 0 2 1] 

Array with Border Ones: 
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]] 

Checkboard Pattern: 
 [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]] 



**Problem - 3: Array Operations:**

In [42]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

addition_result = x + y
print("Addition of x and y: \n", addition_result,"\n")

subtraction_result = x - y
print("Subtraction of x and y: \n", subtraction_result,"\n")

multiplication_result = x * 2
print("Multiplication of x by 2: \n", multiplication_result,"\n")

square_result = x ** 2
print("Square of x in each element: \n", square_result,"\n")


dot_v_w = np.dot(v,w)
dot_x_v = np.dot(x,v)
dot_x_y = np.dot(x,y)

print("Dot Product of v and w: \n", dot_v_w,"\n")
print("Dot Product of x and v: \n", dot_x_v,"\n")
print("Dot Product of x and y: \n", dot_x_y,"\n")

concat_x_y = np.concatenate((x,y), axis=0)
print("Concatenation of X and Y along Rows: \n", concat_x_y,"\n")

concat_v_w = np.vstack((v,w))
print("Concatenation of V and W along Columns: \n", concat_v_w,"\n")

try:
  v_reshaped = v.reshape(1, -1)
  concat_x_v = np.concatenate((x, v_reshaped), axis=0)
  print("Concatenation of x and v:\n", concat_x_v,"\n")
except ValueError as e:
  print("Error: ", e)


Addition of x and y: 
 [[ 6  8]
 [10 12]] 

Subtraction of x and y: 
 [[-4 -4]
 [-4 -4]] 

Multiplication of x by 2: 
 [[2 4]
 [6 8]] 

Square of x in each element: 
 [[ 1  4]
 [ 9 16]] 

Dot Product of v and w: 
 219 

Dot Product of x and v: 
 [29 67] 

Dot Product of x and y: 
 [[19 22]
 [43 50]] 

Concatenation of X and Y along Rows: 
 [[1 2]
 [3 4]
 [5 6]
 [7 8]] 

Concatenation of V and W along Columns: 
 [[ 9 10]
 [11 12]] 

Concatenation of x and v:
 [[ 1  2]
 [ 3  4]
 [ 9 10]] 



**Problem - 4: Matrix Operations:**

In [49]:
A = np.array([[1,2], [3,4]])
B = np.array([[5,6], [7,8]])

#1. Prove A.A⁻¹ = I.
A_Inv = np.linalg.inv(A)
identity_check = np.dot(A, A_Inv)
print("A.A⁻¹ = Identity Matrix: \n", identity_check, "\n")

#2. Prove AB ̸= BA
AB = np.dot(A,B)
BA = np.dot(B,A)
print("\nMatrix AB:\n", AB, "\n")
print("\nMatrix BA:\n", BA, "\n")
if not np.array_equal(AB,BA):
  print("AB is not equal to BA")
else:
  print("AB is equal to BA")

#3. Prove (AB)ᵀ = BᵀAᵀ

AB_transpose = np.transpose(AB)
BT_AT = np.dot(B.T, A.T)
print("\n(AB)ᵀ:\n", AB_transpose)
print("\nBᵀ * Aᵀ:\n", BT_AT)
if np.array_equal(AB_transpose, BT_AT):
  print("\n(AB)ᵀ = Bᵀ * Aᵀ")
else:
  print("\n(AB)ᵀ ≠ Bᵀ * Aᵀ")


# 4. Solve Linear Equations using Inverse Methods
# System of equations:
#  2x - 3y + z = -1
#  x - y + 2z = -3
#  3x + y - z = 9

A_matrix = np.array([[2,-3,1],
                     [1,-1,2],
                     [3,1,-1]])

B_Matrix = np.array([-1,-3,9])

A_Inv = np.linalg.inv(A_matrix)
solution = np.dot(A_Inv, B_Matrix)
print("\nSolution using Inverse Method:\n", solution)

A.A⁻¹ = Identity Matrix: 
 [[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]] 


Matrix AB:
 [[19 22]
 [43 50]] 


Matrix BA:
 [[23 34]
 [31 46]] 

AB is not equal to BA

(AB)ᵀ:
 [[19 43]
 [22 50]]

Bᵀ * Aᵀ:
 [[19 43]
 [22 50]]

(AB)ᵀ = Bᵀ * Aᵀ

Solution using Inverse Method:
 [ 2.  1. -2.]


**Experiment: How Fast is Numpy?**

In [66]:
import time

size = 1_00_000
matrix_size = 1000

#Generate Random data
list1 = [i for i in range(size)]
list2 = [i for i in range(size)]

array1 = np.arange(size)
array2 = np.arange(size)

# 1. Element-wise Addition
# Using Python Lists
start_time = time.time()
list_addition = [list1[i] + list2[i] for i in range(size)]
list_addidtion_time = time.time() - start_time
print(f"Python Lists Addition Time: {list_addidtion_time: .5f} seconds")

# Using numpy array
start_time = time.time()
numpy_addition = array1 + array2
numpy_addition_time = time.time() - start_time
print(f"NumPy Arrays Addition Time: {numpy_addition_time:.5f} seconds \n")

# 2. Element-wise Multiplication
# Using Python Lists
start_time = time.time()
list_multiplication = [list1[i] * list2[i] for i in range(size)]
list_multiplication_time = time.time() - start_time
print(f"Python Lists Multiplication Time: {list_multiplication_time: .5f} seconds")

# Using numpy array
start_time = time.time()
numpy_multiplication = array1 * array2
numpy_multiplication_time = time.time() - start_time
print(f"NumPy Arrays Multiplication Time: {numpy_multiplication_time:.5f} seconds \n")


# 3. Dot Product
# Using Python Lists
start_time = time.time()
dot_product = sum(list1[i] * list2[i] for i in range(size))
list_dot_product_time = time.time() - start_time
print(f"Python Lists Dot Product Time: {list_dot_product_time: .5f} seconds")

# Using numpy array
start_time = time.time()
numpy_dot_product = np.dot(array1, array2)
numpy_dot_product_time = time.time() - start_time
print(f"NumPy Arrays Dot Product Time: {numpy_dot_product_time:.5f} seconds \n")

# 4. Matrix Multiplication
# Generate random matrices
list_matrix1 = [[j for j in range(matrix_size)] for i in range(matrix_size)]
list_matrix2 = [[j for j in range(matrix_size)] for i in range(matrix_size)]

numpy_matrix1 = np.arange(matrix_size ** 2).reshape(matrix_size, matrix_size)
numpy_matrix2 = np.arange(matrix_size ** 2).reshape(matrix_size, matrix_size)

# Using Python Lists
start_time = time.time()
result_matrix = [[sum(a * b for a, b in zip(row, col)) for col in zip(*list_matrix2)] for row in list_matrix1]
list_matrix_multiplication_time = time.time() - start_time
print(f"Python Lists Matrix Multiplication Time: {list_matrix_multiplication_time:.5f} seconds")

# Using NumPy Arrays
start_time = time.time()
numpy_matrix_multiplication = np.dot(numpy_matrix1, numpy_matrix2)
numpy_matrix_multiplication_time = time.time() - start_time
print(f"NumPy Arrays Matrix Multiplication Time: {numpy_matrix_multiplication_time:.5f} seconds \n")

Python Lists Addition Time:  0.00581 seconds
NumPy Arrays Addition Time: 0.00051 seconds 

Python Lists Multiplication Time:  0.00620 seconds
NumPy Arrays Multiplication Time: 0.00034 seconds 

Python Lists Dot Product Time:  0.00900 seconds
NumPy Arrays Dot Product Time: 0.00030 seconds 

Python Lists Matrix Multiplication Time: 179.49689 seconds
NumPy Arrays Matrix Multiplication Time: 3.16528 seconds 

